name: PostMortal
favicon: null
layout_spectrum: 0.4265151859726757
typography_spectrum: 0.782386107603088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5331419829744846
  lightness: 0.04472861159592867
  saturation: 0.3813768089748919
  rhythmicContrast: 0.6570193730294704
purpose: []
